import type { Manga, Review, ForumThread } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const findImage = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  if (!image) {
    // Fallback if image not found
    return {
      id,
      description: 'Placeholder image',
      imageUrl: 'https://picsum.photos/seed/placeholder/400/600',
      imageHint: 'manga cover',
    };
  }
  return image;
};

export const mangaData: Manga[] = [
  {
    id: '1',
    title: 'Echoes of the Void',
    author: 'Yuki Tanaka',
    genres: ['Sci-Fi', 'Mystery', 'Psychological'],
    description: 'In a future where humanity has colonized the stars, a lone investigator must solve a series of mysterious deaths on a remote outpost, only to uncover a secret that could unravel civilization.',
    coverImage: findImage('manga-1'),
    popularity: 95,
    releaseDate: '2023-05-20',
    chapters: 78,
  },
  {
    id: '2',
    title: 'The Last Spellbinder',
    author: 'Kenji Sato',
    genres: ['Fantasy', 'Adventure', 'Magic'],
    description: 'In a world where magic is fading, a young girl discovers she is the last one with the power to bind spells. She embarks on a journey to restore magic, hunted by those who want to extinguish it forever.',
    coverImage: findImage('manga-2'),
    popularity: 98,
    releaseDate: '2022-11-10',
    chapters: 120,
  },
  {
    id: '3',
    title: 'Kyoto Ghost Stories',
    author: 'Rina Suzuki',
    genres: ['Horror', 'Supernatural', 'Slice of Life'],
    description: 'A collection of chilling tales about a group of high school students who encounter the supernatural entities haunting the ancient city of Kyoto. Each chapter is a new ghostly encounter.',
    coverImage: findImage('manga-3'),
    popularity: 85,
    releaseDate: '2024-01-15',
    chapters: 45,
  },
  {
    id: '4',
    title: 'Cyber Ronin',
    author: 'Tetsuo Mori',
    genres: ['Cyberpunk', 'Action', 'Sci-Fi'],
    description: 'In the neon-drenched metropolis of Neo-Kyoto, a disgraced cyber-samurai with a mysterious past takes on dangerous jobs to survive, all while being hunted by a powerful corporation.',
    coverImage: findImage('manga-4'),
    popularity: 92,
    releaseDate: '2023-09-01',
    chapters: 62,
  },
  {
    id: '5',
    title: 'Love in Tokyo',
    author: 'Airi Honda',
    genres: ['Romance', 'Comedy', 'Slice of Life'],
    description: 'A heartwarming and hilarious story of two unlikely individuals, a quiet librarian and a boisterous street artist, who find love in the bustling city of Tokyo.',
    coverImage: findImage('manga-5'),
    popularity: 88,
    releaseDate: '2021-06-30',
    chapters: 150,
  },
  {
    id: '6',
    title: 'Galactic Drifters',
    author: 'Haru Yamamoto',
    genres: ['Sci-Fi', 'Space Opera', 'Adventure'],
    description: 'The ragtag crew of the starship "Stardust" travels across the galaxy taking on odd jobs, getting into trouble, and searching for a legendary treasure that could change their lives.',
    coverImage: findImage('manga-6'),
    popularity: 89,
    releaseDate: '2023-03-12',
    chapters: 95,
  },
  {
    id: '7',
    title: 'The Silent Blade',
    author: 'Goemon Ishikawa',
    genres: ['Action', 'Historical', 'Samurai'],
    description: 'During the tumultuous Sengoku period, a masterless samurai known only as "The Silent Blade" wanders the land, protecting the innocent and upholding his own code of honor.',
    coverImage: findImage('manga-7'),
    popularity: 93,
    releaseDate: '2020-08-25',
    chapters: 180,
  },
  {
    id: '8',
    title: 'Sweet Delusions',
    author: 'Mika Aoyama',
    genres: ['Slice of Life', 'Cooking', 'Romance'],
    description: 'A young woman quits her corporate job to open a small bakery. She soon finds that her pastries have a magical ability to bring happiness and love to her customers.',
    coverImage: findImage('manga-8'),
    popularity: 82,
    releaseDate: '2024-02-28',
    chapters: 35,
  },
  {
    id: '9',
    title: 'Chronicles of Aethel',
    author: 'Emi Ito',
    genres: ['Fantasy', 'Isekai', 'Adventure'],
    description: 'A programmer is reincarnated into the world of her favorite RPG, Aethel. Using her knowledge of the game, she navigates this new reality to become its most powerful adventurer.',
    coverImage: findImage('manga-9'),
    popularity: 96,
    releaseDate: '2022-07-19',
    chapters: 110,
  },
  {
    id: '10',
    title: 'Project Chimera',
    author: 'Dr. Aris Thorne',
    genres: ['Sci-Fi', 'Thriller', 'Biopunk'],
    description: 'A brilliant but disgraced scientist creates a hybrid creature with immense power. When his creation escapes, he must team up with a cynical detective to stop it before it wreaks havoc.',
    coverImage: findImage('manga-10'),
    popularity: 90,
    releaseDate: '2023-12-05',
    chapters: 55,
  },
  {
    id: '11',
    title: 'Gourmet Hunter',
    author: 'Jin Kobayashi',
    genres: ['Adventure', 'Cooking', 'Fantasy'],
    description: 'In a world filled with fantastical beasts and exotic ingredients, a legendary Gourmet Hunter travels the globe to find the rarest foods and create the ultimate full-course meal.',
    coverImage: findImage('manga-11'),
    popularity: 91,
    releaseDate: '2019-10-10',
    chapters: 210,
  },
   {
    id: '12',
    title: 'The Clockwork Alchemist',
    author: 'Isabella Vance',
    genres: ['Steampunk', 'Fantasy', 'Mystery'],
    description: 'In a Victorian-esque city powered by steam and alchemy, a young inventor must unravel a conspiracy that threatens to bring down the entire government, with only her wits and clockwork creations to help her.',
    coverImage: findImage('manga-12'),
    popularity: 87,
    releaseDate: '2024-04-01',
    chapters: 25,
  },
];

export const reviewsData: Review[] = [
  {
    id: 'r1',
    mangaId: '2',
    user: 'MangaFan22',
    avatar: 'https://picsum.photos/seed/avatar1/40/40',
    rating: 5,
    comment: 'Absolutely breathtaking! The world-building is incredible and the main character is so inspiring. A must-read for any fantasy lover.',
    date: '2024-05-10',
  },
  {
    id: 'r2',
    mangaId: '2',
    user: 'FantasyGuru',
    avatar: 'https://picsum.photos/seed/avatar2/40/40',
    rating: 4,
    comment: 'A great take on the "magic is disappearing" trope. The art is beautiful, though the pacing can be a bit slow at times. Still, highly recommended.',
    date: '2024-05-08',
  },
  {
    id: 'r3',
    mangaId: '4',
    user: 'CyberGeek',
    avatar: 'https://picsum.photos/seed/avatar3/40/40',
    rating: 5,
    comment: 'Peak cyberpunk. The action is intense, the world feels alive, and the protagonist is a total badass. I can\'t wait for the next chapter!',
    date: '2024-04-20',
  },
  {
    id: 'r4',
    mangaId: '5',
    user: 'RomComReader',
    avatar: 'https://picsum.photos/seed/avatar4/40/40',
    rating: 4,
    comment: 'So cute and funny! It always puts a smile on my face. If you need a feel-good story, this is it.',
    date: '2024-03-15',
  },
];

export const forumThreads: ForumThread[] = [
    {
        id: 't1',
        title: 'Which manga has the best art style in your opinion?',
        author: 'ArtLover99',
        date: '2024-05-12',
        replies: 42,
        lastReply: { author: 'InkMaster', date: '2024-05-15' },
    },
    {
        id: 't2',
        title: 'Predictions for the final arc of "The Last Spellbinder"',
        author: 'FantasyGuru',
        date: '2024-05-11',
        replies: 128,
        lastReply: { author: 'SpoilerKing', date: '2024-05-15' },
    },
    {
        id: 't3',
        title: 'Underrated Sci-Fi manga you should be reading',
        author: 'SpaceCadet',
        date: '2024-05-10',
        replies: 76,
        lastReply: { author: 'SciFiFan', date: '2024-05-14' },
    },
    {
        id: 't4',
        title: 'Favorite romance manga of all time?',
        author: 'HeartEyes',
        date: '2024-05-09',
        replies: 99,
        lastReply: { author: 'RomComReader', date: '2024-05-13' },
    },
    {
        id: 't5',
        title: 'Welcome to MangaVerse! Introduce yourself!',
        author: 'Admin',
        date: '2024-05-01',
        replies: 215,
        lastReply: { author: 'Newbie1', date: '2024-05-15' },
    }
];
